"""
Plant AI Vision - PDF Diagnostic Report Generator
Generates clean PDF diagnostic reports using FPDF.
Includes text sanitization for Unicode & Latin-1 compatibility.
"""

import os
import time
from fpdf import FPDF

def sanitize_text(text):
    """Sanitize text to replace non-latin1 unicode characters for FPDF compatibility."""
    if not isinstance(text, str):
        return str(text)
    
    replacements = {
        "\u2014": "-",   # em dash
        "\u2013": "-",   # en dash
        "\u201c": '"',   # left double quote
        "\u201d": '"',   # right double quote
        "\u2018": "'",   # left single quote
        "\u2019": "'",   # right single quote
        "\u00b0": " deg ", # degree symbol
        "°": " deg ",
    }
    for orig, repl in replacements.items():
        text = text.replace(orig, repl)

    return text.encode('latin-1', 'replace').decode('latin-1')

class DiagnosticPDFReport(FPDF):
    """Custom FPDF class for generating professional agronomic reports."""

    def header(self):
        self.set_font('Helvetica', 'B', 15)
        self.set_text_color(22, 101, 52)  # Dark Forest Green
        self.cell(0, 8, 'PLANT VISION AI - DIAGNOSTIC REPORT', 0, 1, 'C')
        self.set_font('Helvetica', 'I', 8.5)
        self.set_text_color(100, 116, 139)
        self.cell(0, 5, 'PyTorch CNN Classifier & Live Climate Intelligence', 0, 1, 'C')
        self.ln(3)
        self.set_draw_color(34, 197, 94)
        self.set_line_width(0.5)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(148, 163, 184)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by Plant Vision AI', 0, 0, 'C')

def generate_pdf_report(data, output_path):
    """
    Build PDF report containing analysis metrics, weather, soil, and AI advice.
    """
    pdf = DiagnosticPDFReport()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    cnn = data.get("cnn_prediction", {})
    weather = data.get("weather_data", {})
    ai = data.get("ai_insights", {})
    fert = data.get("fertilizer_advice", {})

    epw = 180  # Effective page width for 210mm A4 with 15mm margins

    # 1. Summary Header Box
    pdf.set_font('Helvetica', 'B', 12)
    pdf.set_text_color(15, 23, 42)
    pdf.set_x(15)
    pdf.cell(epw, 7, sanitize_text(f"Condition Detected: {cnn.get('display_name', 'Plant Condition')}"), 0, 1, 'L')

    pdf.set_font('Helvetica', '', 9.5)
    pdf.set_text_color(71, 85, 105)
    pdf.set_x(15)
    pdf.cell(90, 5, sanitize_text(f"Confidence Score: {cnn.get('confidence')}%"), 0, 0, 'L')
    pdf.cell(90, 5, sanitize_text(f"Severity Index: {cnn.get('metadata', {}).get('severity', 'Medium')}"), 0, 1, 'L')

    loc_name = weather.get("location_name", "Regional Zone") if weather else "Regional Zone"
    temp = f"{weather.get('temperature_c')} deg C" if weather else "N/A"
    humidity = f"{weather.get('humidity_pct')}%" if weather else "N/A"
    soil_type = weather.get("soil", {}).get("soil_type", "Loamy Soil") if weather else "Loamy Soil"

    pdf.set_x(15)
    pdf.cell(90, 5, sanitize_text(f"Location: {loc_name}"), 0, 0, 'L')
    pdf.cell(90, 5, sanitize_text(f"Climate: {temp}, {humidity} Humidity"), 0, 1, 'L')
    pdf.set_x(15)
    pdf.cell(epw, 5, sanitize_text(f"Regional Soil Profile: {soil_type}"), 0, 1, 'L')
    pdf.ln(4)

    # 2. Add Uploaded Leaf Image if available
    img_path = data.get("image_path")
    if img_path and os.path.exists(img_path):
        try:
            pdf.image(img_path, x=15, w=70)
            pdf.ln(4)
        except Exception as e:
            print(f"[PDF] Image insert error: {e}")

    # Helper function to write multi-cell section cleanly
    def write_section(title, content_list, fill_color=(240, 253, 244), text_color=(22, 101, 52)):
        pdf.set_fill_color(*fill_color)
        pdf.set_font('Helvetica', 'B', 10.5)
        pdf.set_text_color(*text_color)
        pdf.set_x(15)
        pdf.cell(epw, 7, sanitize_text(f"  {title}"), 1, 1, 'L', fill=True)
        pdf.set_font('Helvetica', '', 9)
        pdf.set_text_color(30, 41, 59)
        
        if isinstance(content_list, str):
            pdf.set_x(15)
            pdf.multi_cell(epw, 5, sanitize_text(content_list))
        elif isinstance(content_list, list):
            for item in content_list:
                pdf.set_x(15)
                pdf.multi_cell(epw, 5, sanitize_text(f"- {item}"))
        pdf.ln(3)

    # 3. Pathology Diagnosis
    write_section("1. Visual Pathology & Diagnosis", ai.get("ai_diagnosis", "No detailed diagnosis text."))

    # 4. Organic Treatment Protocol
    write_section("2. Organic Treatment Protocol", ai.get("organic_remedies", []), (240, 253, 244), (22, 101, 52))

    # 5. Chemical Interventions
    write_section("3. Chemical & Fungicidal Interventions", ai.get("chemical_treatments", []), (254, 243, 199), (180, 83, 9))

    # 6. N-P-K Fertilizer Plan
    if fert:
        fert_text = [
            f"Target N-P-K Ratio: {fert.get('target_npk_ratio')}",
            f"Organic Formula: {fert.get('organic_formula')}",
            f"Foliar Dosage: {fert.get('chemical_dosage')}",
            f"Schedule: {fert.get('application_schedule')}"
        ]
        write_section("4. Smart N-P-K Nutrient & Fertilizer Plan", fert_text, (236, 253, 245), (15, 118, 110))

    # 7. Climate & Agronomic Advisory
    write_section("5. Climate & Soil Advisory", ai.get("preventive_advisory", []), (241, 245, 249), (15, 23, 42))

    pdf.set_font('Helvetica', 'I', 9.5)
    pdf.set_text_color(22, 101, 52)
    pdf.set_x(15)
    quote_text = sanitize_text(f"Expert Advice: \"{ai.get('expert_quote', 'Maintain regular crop monitoring.')}\"")
    pdf.multi_cell(epw, 5, quote_text)

    pdf.output(output_path)
    return output_path
